### ISSUE TITLE
No base URL

### ISSUE THREAD

**Issue by JPBoero** [noboomu/ARFaceKit#1]
Hi!, i have tried to build with the latest xcode to this date, and i have to replace the current opencv framework with one from the web page, then when trying to run it crashed on this line:

return Bundle.main.object(forInfoDictionaryKey: "WRLAPIBaseURL") as! String

Looks like a dict is missing to get a base URL.

Thanks.

**Comment by noboomu** [comment]
Sorry JP! I'm just seeing this :( Hopefully you are playing with VisionOS at this point.
